export const BPM_LIST = [
    50,
    55,
    60,
    65, 
    70, 
    75,
    80, 
    85,
    90,
    95,
    100,
    105,
    110,
    115,
    120,
    125,
    128,
    130,
    135,
    140,
    150,
    160,
    170,
    172,
    175,
    180,
    200,
];

export const GENRE_LIST = [
    'Glitch Hop',
    'Breakbeat',
    'Dub',
    'Tech House',
    'Future House',
    'Future Bass',
    'Trap',
    'Twerk',
    'Footwork',
    'Jungle',
    'Reggae',
    'Ragga',
    'Reggaeton',
    'Dancehall Reggae',
    'Rock',
    'Alternative Rock',
    'Hard Rock',
    'Heavy Metal',
    'Euro Trance',
    'Psy-Trance',
    'Dark Psy-Trance',
    'Full On',
    'Dark Full On',
    'Morning Psy-Trance',
    'Jazz',
    'Jazzy Hip Hop',
    'Hip Hop',
    'Noise',
    'Jazzstep',
    'Fusion',
    'Orchestral',
    'Funk',
    'Blues',
    'Chiptune',
    'Fakebit',
    'Micro Funk',
    'Tropical House',
    'EDM',
    'House',
    'Hard House',
    'Electro House',
    'Progressive House',
    'Disco',
    'Nu Disco',
    'Trance',
    'Progressive Trance',
    'Cyber Trance',
    'Uplifting Trance',
    'Hard Trance',
    'Tech Trance',
    'Tech Dance',
    'Hands Up',
    'Rave',
    'Dubstep',
    'Drumstep',
    'Drum & Bass',
    'Neurofunk',
    'New Age',
    'Pops',
    'Irish',
    'Celtish',
    'Spanish',
    '純邦楽',
    'Ambient',
    'Autonomic',
    'Minimal',
    'Electro',
    'Electronica',
    'Synth Pop',
    'Bubblegum Dance',
    'Makina',
    'Hardcore',
    'Happy Hardcore',
    'UK Hardcore',
    'Speedcore',
    'Symphony',
];